Repository akademia-envelo-3/meetek-front, pull requests merged in 2023-01, with the labels that each got.

#29 feat: add netlify basic deployment config
  netlify.toml
Labels: tech

#24 FT002 - feat: added json server and json server auth
  .gitignore
  package-lock.json
  package.json
Labels: cr

#26 FT019 - feat: added routing paths
  src/app/features/auth/auth.module.ts
  src/app/features/home/home.module.ts
Labels: cr

#28 FT001 - feat: modification Material Design theming
  README.md
  src/styles.scss
Labels: cr

#27 FT018 - feat: added endpoints
  src/app/shared/api/endpoints.ts
Labels: cr

#31 FT021-add-store-for-sections
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/features/home/home.module.ts
  src/app/features/section/index.ts
  src/app/features/section/section.component.ts
  src/app/features/section/shared/interfaces/event.interface.ts
  src/app/features/section/shared/interfaces/hashtag.interface.ts
  src/app/features/section/shared/interfaces/index.ts
  src/app/features/section/shared/interfaces/section.interface.ts
  src/app/features/section/shared/interfaces/user.interface.ts
  src/app/features/section/store/section.actions.ts
  src/app/features/section/store/section.effects.ts
  src/app/features/section/store/section.reducer.ts
  src/app/features/section/store/section.selectors.ts
  src/app/features/section/store/section.service.ts
  src/app/features/section/store/section.state.ts
  src/styles.scss
  tsconfig.app.json
Labels: cr, no-test

#30 Ft006: feat stworzenie formularza logowania z walidacja
  angular.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/core/store/user.actions.ts
  src/app/core/store/user.effects.ts
  src/app/core/store/user.interfaces.ts
  src/app/core/store/user.reducer.ts
  src/app/core/store/user.selectors.ts
  src/app/core/store/user.service.ts
  src/app/core/store/user.state.ts
  src/app/features/auth/auth.component.html
  src/app/features/auth/auth.component.scss
  src/app/features/auth/auth.component.ts
  src/app/features/auth/auth.module.ts
  src/app/features/auth/auth.service.ts
  src/app/features/auth/form/form.component.html
  src/app/features/auth/form/form.component.scss
  src/app/features/auth/form/form.component.ts
  src/app/features/auth/form/validators/form.validators.ts
  src/app/features/auth/index.ts
  src/app/features/auth/shared/auth.interfaces.ts
  src/app/features/auth/store/auth.actions.ts
  src/app/features/auth/store/auth.effects.ts
  src/app/shared/styles/breakpoints.scss
  src/assets/images/logo.svg
  src/styles.scss
Labels: cr

#33 FT013 - feat: added section-card component
  src/app/core/theme.component.ts
  src/app/features/section/index.ts
  src/app/features/section/shared/section-card/section-card.component.html
  src/app/features/section/shared/section-card/section-card.component.scss
  src/app/features/section/shared/section-card/section-card.component.ts
  src/styles.scss
Labels: test ok

#58 FT024 feat: serwis do obsługi toastów
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/core/store/user.effects.ts
  src/app/features/auth/store/auth.effects.ts
  src/app/features/section/store/section.effects.ts
  src/app/shared/services/index.ts
  src/app/shared/services/toast.facade.service.ts
  src/styles.scss
Labels: frontend, feat

#36 feat: add logic and styles for list of the section members
  src/app/core/theme.component.scss
  src/app/core/theme.component.ts
  src/app/features/home/home.component.ts
  src/app/features/home/home.module.ts
  src/app/features/section/index.ts
  src/app/features/section/shared/interfaces/event.interface.ts
  src/app/features/section/shared/interfaces/section.interface.ts
  src/app/features/section/shared/interfaces/user.interface.ts
  src/app/features/section/shared/list/list-item/member-list-item.component.html
  src/app/features/section/shared/list/list-item/member-list-item.component.scss
  src/app/features/section/shared/list/list-item/member-list-item.component.ts
  src/app/features/section/shared/list/member-list/member-list.component.html
  src/app/features/section/shared/list/member-list/member-list.component.scss
  src/app/features/section/shared/list/member-list/member-list.component.ts
  src/app/features/section/store/section.actions.ts
  src/app/features/section/store/section.effects.ts
  src/app/features/section/store/section.reducer.ts
  src/app/features/section/store/section.selectors.ts
  src/app/features/section/store/section.service.ts
  src/app/features/section/store/section.state.ts
  src/app/features/section/subpages/section-members.component.html
  src/app/features/section/subpages/section-members.component.scss
  src/app/features/section/subpages/section-members.component.ts
  src/styles.scss
Labels: cr

#75 feat: add interceptor for handling http errors
  src/app/app.module.ts
  src/app/shared/interceptors/http-error-interceptor.ts
  src/app/shared/interceptors/index.ts
Labels: frontend, tech

#84 FT000-fix-http-interceptor
  src/app/shared/interceptors/http-error-interceptor.ts
Labels: HOTFIX, no-test

#85 fix: fix http interceptor
  src/app/shared/interceptors/http-error-interceptor.ts
Labels: HOTFIX

#83 FT028-nawigacja-event-sekcja
  src/app/features/section/shared/list/list-item/index.ts
  src/app/features/section/shared/list/member-list/index.ts
  src/app/features/section/shared/list/member-list/member-list.component.ts
  src/app/features/section/shared/section-card/index.ts
  src/app/features/section/store/index.ts
  src/app/features/section/subpages/section-members.component.html
  src/app/features/section/subpages/section-members.component.ts
  src/app/shared/interceptors/http-error-interceptor.ts
  src/app/shared/ui/index.ts
  src/app/shared/ui/navigation/navigation.component.html
  src/app/shared/ui/navigation/navigation.component.scss
  src/app/shared/ui/navigation/navigation.component.ts
  src/app/shared/ui/navigation/navigation.iinterface.ts
Labels: frontend, feat, cr
