Repository akademia-envelo-3/meetek-front, pull requests merged in 2023-02, with the labels that each got.

#62 Ft008 feat stworzenie formularza do dodawania sekcji
  src/app/app.module.ts
  src/app/core/store/user.service.ts
  src/app/features/auth/auth.component.scss
  src/app/features/auth/auth.component.ts
  src/app/features/auth/auth.module.ts
  src/app/features/auth/form/form.component.html
  src/app/features/auth/store/auth.effects.ts
  src/app/features/home/home.module.ts
  src/app/features/section/index.ts
  src/app/features/section/shared/interfaces/section-form.interface.ts
  src/app/features/section/shared/interfaces/section.interface.ts
  src/app/features/section/store/section.actions.ts
  src/app/features/section/store/section.effects.ts
  src/app/features/section/store/section.reducer.ts
  src/app/features/section/store/section.service.ts
  src/app/features/section/store/section.state.ts
  src/app/features/section/subpages/section-form/form/form.component.html
  src/app/features/section/subpages/section-form/form/form.component.scss
  src/app/features/section/subpages/section-form/form/form.component.ts
  src/app/features/section/subpages/section-form/form/validators/form.validators.ts
  src/app/features/section/subpages/section-form/index.ts
  src/app/features/section/subpages/section-form/section-form.component.html
  src/app/features/section/subpages/section-form/section-form.component.scss
  src/app/features/section/subpages/section-form/section-form.component.ts
  src/styles.scss
Labels: cr

#79 Ft032 edycja sekcji
  src/app/core/store/user.service.ts
  src/app/features/home/home.module.ts
  src/app/features/section/index.ts
  src/app/features/section/shared/list/member-list/member-list.component.ts
  src/app/features/section/store/section.actions.ts
  src/app/features/section/store/section.effects.ts
  src/app/features/section/store/section.reducer.ts
  src/app/features/section/store/section.selectors.ts
  src/app/features/section/store/section.service.ts
  src/app/features/section/store/section.state.ts
  src/app/features/section/subpages/edit-form/edit-form.component.html
  src/app/features/section/subpages/edit-form/edit-form.component.scss
  src/app/features/section/subpages/edit-form/edit-form.component.ts
  src/app/features/section/subpages/edit-form/form/form.component.html
  src/app/features/section/subpages/edit-form/form/form.component.scss
  src/app/features/section/subpages/edit-form/form/form.component.ts
  src/app/features/section/subpages/edit-form/form/validators/form.validators.ts
  src/app/features/section/subpages/edit-form/index.ts
  src/app/features/section/subpages/section-members/section-members.component.html
  src/app/features/section/subpages/section-members/section-members.component.scss
  src/app/features/section/subpages/section-members/section-members.component.ts
Labels: cr

#102 FT058 fix import
  src/app/features/auth/auth.component.ts
Labels: bug, HOTFIX

#100 Ft009 widok kategorii
  src/app/features/categories/categories.component.html
  src/app/features/categories/categories.component.scss
  src/app/features/categories/categories.component.ts
  src/app/features/categories/index.ts
  src/app/features/categories/shared/categories-card/categories-card.component.html
  src/app/features/categories/shared/categories-card/categories-card.component.scss
  src/app/features/categories/shared/categories-card/categories-card.component.ts
  src/app/features/categories/shared/interfaces/categories.interfaces.ts
  src/app/features/categories/store/categories.service.ts
  src/app/features/categories/store/categories.store.ts
  src/app/features/home/home.component.scss
  src/app/features/home/home.module.ts
  src/app/shared/ui/category-hashtag-card/category-hashtag-card.component.html
  src/app/shared/ui/category-hashtag-card/category-hashtag-card.component.scss
  src/app/shared/ui/category-hashtag-card/category-hashtag-card.component.ts
Labels: cr

#94 Ft017 wyswietlanie sekcji
  src/app/features/home/home-paths.ts
  src/app/features/home/home.component.scss
  src/app/features/home/home.module.ts
  src/app/features/section/index.ts
  src/app/features/section/subpages/section-details/section-details.component.html
  src/app/features/section/subpages/section-details/section-details.component.scss
  src/app/features/section/subpages/section-details/section-details.component.ts
  src/app/features/section/subpages/section-members/section-members.component.scss
  src/app/shared/ui/navigation/navigation.component.html
  src/app/shared/ui/navigation/navigation.component.ts
Labels: cr

#90 FT046-feat-loader
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/features/auth/auth.component.html
  src/app/features/auth/auth.component.scss
  src/app/features/auth/auth.component.ts
  src/app/features/home/home.component.html
  src/app/features/home/home.component.scss
  src/app/features/home/home.component.ts
  src/app/shared/interceptors/index.ts
  src/app/shared/interceptors/loader.interceptor.ts
  src/app/shared/services/index.ts
  src/app/shared/services/loader.state.service.ts
  src/app/shared/ui/index.ts
  src/app/shared/ui/spinner/spinner.component.html
  src/app/shared/ui/spinner/spinner.component.ts
Labels: frontend, tech, feat, cr

#98 FT053-store-dla-eventów
  src/app/core/theme.component.ts
  src/app/features/event/index.ts
  src/app/features/event/store/event.actions.ts
  src/app/features/event/store/event.effects.ts
  src/app/features/event/store/event.reducer.ts
  src/app/features/event/store/event.selectors.ts
  src/app/features/event/store/event.service.ts
  src/app/features/event/store/event.state.ts
  src/app/features/home/home.module.ts
  src/app/features/section/index.ts
  src/app/features/section/shared/list/list-item/member-list-item.component.ts
  src/app/features/section/store/section.actions.ts
  src/app/features/section/store/section.state.ts
  src/app/shared/interfaces/event.interface.ts
  src/app/shared/interfaces/hashtag.interface.ts
  src/app/shared/interfaces/index.ts
  src/app/shared/interfaces/section-form.interface.ts
  src/app/shared/interfaces/section.interface.ts
  src/app/shared/interfaces/user.interface.ts
Labels: frontend, feat, cr

#82 FT014 Wyswietlenie widoku wszystkich sekcji
  src/app/core/theme.component.ts
  src/app/features/event/store/event.effects.ts
  src/app/features/home/home.module.ts
  src/app/features/section/index.ts
  src/app/features/section/section.component.ts
  src/app/features/section/sections.component.html
  src/app/features/section/sections.component.scss
  src/app/features/section/sections.component.ts
  src/app/shared/styles/button.scss
  src/app/shared/ui/modals/cancel-confirm-dialog/cancel-confirm-dialog.component.html
  src/app/shared/ui/modals/input-dialog/input-dialog.component.html
  src/app/shared/ui/search/search.component.ts
Labels: cr
